from .base import Date
from decimal import Decimal
from pydantic import BaseModel
from typing import List


class SOTransactionItem(BaseModel):
    itemid: str = ...
    quantity: Decimal = ...
    price: Decimal = ...


class SOTransactionItems(BaseModel):
    sotransitem: List[SOTransactionItem]


class SOTransaction(BaseModel):
    transactiontype: str = ...
    datecreated: Date = ...
    customerid: str = ...
    datedue: Date = ...
    state: str = ...
    sotransitems: SOTransactionItems = ...
